name: Build Image

on:
  push:
    branches: 
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: progrium/env86:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create image
        run: |
          env86 create --from-docker=./Dockerfile ./image
          env86 boot --cdp --cold --ttyS0 --save --no-console --exit-on="localhost:~#" ./image
          tar -czf alpine-3.18.tgz -C image .

      - uses: ncipollo/release-action@v1
        with:
          tag: "3.18"
          allowUpdates: true
          artifacts: "alpine-3.18.tgz"