name: Build Image?

on:
  push:
    branches: 
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: progrium/env86:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: /work

      - name: Test env86
        run: |
          cd /work && ls -la
          env86 create --from-docker=/work/Dockerfile ./image
          ls -la ./image

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: image