name: Build Image?

on:
  push:
    branches: 
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: progrium/env86:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test env86
        run: |
          env86 create --from-docker=./Dockerfile ./image
          tar -czf alpine.tgz -C image .

      - uses: ncipollo/release-action@v1
        with:
          tag: "v0"
          artifacts: "alpine.tgz"