name: Build Image?

on:
  push:
    branches: 
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io          

      - name: Test env86
        run: |
          ls
          mkdir ./image
          docker pull progrium/env86
          tar -cf - . | docker run -i --privileged -v /var/run/docker.sock:/var/run/docker.sock progrium/env86 sh -c "tar -xf - -C /mnt && env86 create --from-docker=/mnt/Dockerfile ./image && tar -cf - ./image" | tar -xf - -C .
          ls -la ./image

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: image